Repository mozilla-rally/web-science, pull requests merged in 2021-04, with the labels that each got.

#39 Updating the README
  README.md
Labels: documentation

#35 Refactoring to match WebExtensions syntax
  src/content-scripts/linkExposure.content.js
  src/content-scripts/pageContent.content.js
  src/content-scripts/pageManager.content.js
  src/content-scripts/pageNavigation.content.js
  src/events.js
  src/idle.js
  src/linkExposure.js
  src/matching.js
  src/pageClassification.js
  src/pageManager.js
  src/pageNavigation.js
  src/scheduling.js
  src/socialMediaLinkSharing.js
  src/storage.js
  src/userSurvey.js
Labels: study blocker

#41 Adding code of conduct
  CODE_OF_CONDUCT.md
Labels: meta

#37 Refactoring the userSurvey module to remove study-specific code
  rollup.config.final.js
  rollup.config.intermediate.js
  src/contentScripts.js
  src/html/userSurvey.popupNoPrompt.html
  src/html/userSurvey.popupPrompt.html
  src/id.js
  src/inline.js
  src/linkExposure.js
  src/pageClassification.js
  src/pageManager.js
  src/pageNavigation.js
  src/socialMediaActivity.js
  src/userSurvey.js
  src/webScience.js
Labels: study blocker

#43 Lots of documentation fixes
  README.md
  src/content-scripts/linkExposure.content.js
  src/content-scripts/pageNavigation.content.js
  src/content-scripts/socialMediaActivity.facebook.content.js
  src/debugging.js
  src/dependencies/ampCachesAndViewers.js
  src/dependencies/urlShorteners.js
  src/events.js
  src/idle.js
  src/linkExposure.js
  src/linkResolution.js
  src/matching.js
  src/messaging.js
  src/pageClassification.js
  src/pageManager.js
  src/pageNavigation.js
  src/randomization.js
  src/scheduling.js
  src/socialMediaActivity.js
  src/socialMediaLinkSharing.js
  src/storage.js
  src/userSurvey.js
Labels: documentation

#44 Updating IDs to UUIDs
  package-lock.json
  package.json
  src/content-scripts/pageManager.content.js
  src/id.js
Labels: enhancement

#48 Adding basic WebExtensions permissions checking
  README.md
  src/idle.js
  src/linkExposure.js
  src/linkResolution.js
  src/pageManager.js
  src/permissions.js
  src/randomization.js
  src/socialMediaActivity.js
  src/storage.js
  src/userSurvey.js
  src/webScience.js
Labels: documentation, enhancement

#47 Updating messaging to match WebExtensions syntax
  README.md
  src/events.js
  src/linkExposure.js
  src/messaging.js
  src/pageClassification.js
  src/pageManager.js
  src/pageNavigation.js
  src/socialMediaActivity.js
  src/userSurvey.js
Labels: study blocker

#45 Remove code repetition from content scripts
  src/content-scripts/linkExposure.content.js
  src/content-scripts/pageManager.content.js
  src/content-scripts/socialMediaActivity.facebook.content.js
  src/events.js
  src/linkResolution.js
  src/matching.js
  src/pageNavigation.js
  src/socialMediaLinkSharing.js
Labels: enhancement

#46 Updating storage to use WebExtensions local storage
  package-lock.json
  package.json
  src/storage.js
Labels: enhancement

#49 Rewrite for linkResolution.resolveUrl
  README.md
  src/linkExposure.js
  src/linkResolution.js
  src/socialMediaLinkSharing.js
Labels: enhancement

#52 pageNavigation improvements
  src/content-scripts/pageNavigation.content.js
  src/pageNavigation.js
Labels: enhancement

#56 Refactoring pageClassification into pageText
  README.md
  package-lock.json
  package.json
  rollup.config.final.js
  rollup.config.intermediate.js
  src/content-scripts/pageContent.content.js
  src/content-scripts/pageText.content.js
  src/pageClassification.js
  src/pageText.js
  src/webScience.js
  src/worker-scripts/pageText.worker.js
Labels: enhancement

#50 Updates for linkExposure
  README.md
  package-lock.json
  package.json
  src/content-scripts/linkExposure.content.js
  src/linkExposure.js
  src/linkResolution.js
  src/pageManager.js
  src/permissions.js
Labels: enhancement

#62 Adding a workers module for passing events to Web Workers
  README.md
  rollup.config.final.js
  rollup.config.intermediate.js
  src/events.js
  src/idle.js
  src/linkExposure.js
  src/messaging.js
  src/pageManager.js
  src/pageNavigation.js
  src/pageText.js
  src/scheduling.js
  src/socialMediaLinkSharing.js
  src/webScience.js
  src/worker-scripts/pageText.worker.js
  src/workers.js
Labels: enhancement

#63 Completing event model transition for idle
  src/idle.js
Labels: enhancement

#53 Functionality for series of subsequent surveys and updated browser action popup UI
  src/html/userSurvey.popupNoPrompt.html
  src/html/userSurvey.popupPrompt.html
  src/userSurvey.js
Labels: enhancement

#60 Support for Content Security Policy checking
  src/permissions.js
  src/userSurvey.js
Labels: enhancement

#69 Improvements for KeyValueStorage
  src/storage.js
Labels: enhancement
